--[[--------------------------------------------------------------------
	LibRealmInfo
	World of Warcraft library for obtaining information about realms.
	by Phanx <addons@phanx.net>
	https://github.com/phanx/wow-librealminfo
	http://www.curse.com/addons/wow/librealminfo
	http://www.wowinterface.com/downloads/info
----------------------------------------------------------------------]]

local MAJOR, MINOR = "LibRealmInfo", 1
assert(LibStub, MAJOR.." requires LibStub")
local lib, oldminor = LibStub:NewLibrary(MAJOR, MINOR)
if not lib then return end

local data
local standalone = (...) == MAJOR

function lib:GetRealmInfo(realmID)
	local info = data[realmID]
	if info then
		return info.name, info.type, info.language, info.region, info.subregion
	elseif standalone then
		return print("|cffff7f7f["..MAJOR.."]|r No info found for realm", realmID)
	end
end

data = {
--{{ NORTH AMERICA -----------------------------------------------------
[1136] = { name = "Aegwynn", type = "PVP", region = "US", language = "enUS" },
[1284] = { name = "Aerie Peak", type = "PVE", region = "US", language = "enUS" },
[1129] = { name = "Agamaggan", type = "PVP", region = "US", language = "enUS" },
[106] = { name = "Aggramar", type = "PVE", region = "US", language = "enUS" },
[1137] = { name = "Akama", type = "PVP", region = "US", language = "enUS" },
[1070] = { name = "Alexstrasza", type = "PVE", region = "US", language = "enUS" },
[52] = { name = "Alleria", type = "PVE", region = "US", language = "enUS" },
[1282] = { name = "Altar of Storms", type = "PVP", region = "US", language = "enUS" },
[1293] = { name = "Alterac Mountains", type = "PVP", region = "US", language = "enUS" },
[1418] = { name = "Aman'Thul", type = "PVE", region = "US", language = "enUS", subregion = "Oceanic" },
[1276] = { name = "Andorhal", type = "PVP", region = "US", language = "enUS" },
[1264] = { name = "Anetheron", type = "PVP", region = "US", language = "enUS" },
[1363] = { name = "Antonidas", type = "PVE", region = "US", language = "enUS" },
[1346] = { name = "Anub'arak", type = "PVP", region = "US", language = "enUS" },
[1288] = { name = "Anvilmar", type = "PVE", region = "US", language = "enUS" },
[1165] = { name = "Arathor", type = "PVE", region = "US", language = "enUS" },
[56] = { name = "Archimonde", type = "PVP", region = "US", language = "enUS" },
[1566] = { name = "Area 52", type = "PVE", region = "US", language = "enUS" },
[75] = { name = "Argent Dawn", type = "RP", region = "US", language = "enUS" },
[69] = { name = "Arthas", type = "PVP", region = "US", language = "enUS" },
[1297] = { name = "Arygos", type = "PVE", region = "US", language = "enUS" },
[1555] = { name = "Auchindoun", type = "PVP", region = "US", language = "enUS" },
[77] = { name = "Azgalor", type = "PVP", region = "US", language = "enUS" },
[121] = { name = "Azjol-Nerub", type = "PVE", region = "US", language = "enUS" },
[3209] = { name = "Azralon", type = "PVP", region = "US", language = "ptBR" },
[1128] = { name = "Azshara", type = "PVP", region = "US", language = "enUS" },
[1549] = { name = "Azuremyst", type = "PVE", region = "US", language = "enUS" },
[1190] = { name = "Baelgun", type = "PVE", region = "US", language = "enUS" },
[1075] = { name = "Balnazzar", type = "PVP", region = "US", language = "enUS" },
[1419] = { name = "Barthilas", type = "PVP", region = "US", language = "enUS", subregion = "Oceanic" },
[1280] = { name = "Black Dragonflight", type = "PVP", region = "US", language = "enUS" },
[54] = { name = "Blackhand", type = "PVE", region = "US", language = "enUS" },
[10] = { name = "Blackrock", type = "PVP", region = "US", language = "enUS" },
[1347] = { name = "Blackwater Raiders", type = "RP", region = "US", language = "enUS" },
[1296] = { name = "Blackwing Lair", type = "PVP", region = "US", language = "enUS" },
[1564] = { name = "Blade's Edge", type = "PVE", region = "US", language = "enUS" },
[1353] = { name = "Bladefist", type = "PVE", region = "US", language = "enUS" },
[73] = { name = "Bleeding Hollow", type = "PVP", region = "US", language = "enUS" },
[1558] = { name = "Blood Furnace", type = "PVP", region = "US", language = "enUS" },
[64] = { name = "Bloodhoof", type = "PVE", region = "US", language = "enUS" },
[119] = { name = "Bloodscalp", type = "PVP", region = "US", language = "enUS" },
[83] = { name = "Bonechewer", type = "PVP", region = "US", language = "enUS" },
[1371] = { name = "Borean Tundra", type = "PVE", region = "US", language = "enUS" },
[112] = { name = "Boulderfist", type = "PVP", region = "US", language = "enUS" },
[117] = { name = "Bronzebeard", type = "PVE", region = "US", language = "enUS" },
[91] = { name = "Burning Blade", type = "PVP", region = "US", language = "enUS" },
[102] = { name = "Burning Legion", type = "PVP", region = "US", language = "enUS" },
[1430] = { name = "Caelestrasz", type = "PVE", region = "US", language = "enUS", subregion = "Oceanic" },
[1361] = { name = "Cairne", type = "PVE", region = "US", language = "enUS" },
[88] = { name = "Cenarion Circle", type = "RP", region = "US", language = "enUS" },
[2] = { name = "Cenarius", type = "PVE", region = "US", language = "enUS" },
[1067] = { name = "Cho'gall", type = "PVP", region = "US", language = "enUS" },
[1138] = { name = "Chromaggus", type = "PVP", region = "US", language = "enUS" },
[1556] = { name = "Coilfang", type = "PVP", region = "US", language = "enUS" },
[107] = { name = "Crushridge", type = "PVP", region = "US", language = "enUS" },
[109] = { name = "Daggerspine", type = "PVP", region = "US", language = "enUS" },
[66] = { name = "Dalaran", type = "PVE", region = "US", language = "enUS" },
[1278] = { name = "Dalvengyr", type = "PVP", region = "US", language = "enUS" },
[157] = { name = "Dark Iron", type = "PVP", region = "US", language = "enUS" },
[120] = { name = "Darkspear", type = "PVP", region = "US", language = "enUS" },
[1351] = { name = "Darrowmere", type = "PVE", region = "US", language = "enUS" },
[1434] = { name = "Dath'Remar", type = "PVE", region = "US", language = "enUS", subregion = "Oceanic" },
[1582] = { name = "Dawnbringer", type = "PVE", region = "US", language = "enUS" },
[15] = { name = "Deathwing", type = "PVP", region = "US", language = "enUS" },
[1286] = { name = "Demon Soul", type = "PVP", region = "US", language = "enUS" },
[1271] = { name = "Dentarg", type = "PVE", region = "US", language = "enUS" },
[79] = { name = "Destromath", type = "PVP", region = "US", language = "enUS" },
[81] = { name = "Dethecus", type = "PVP", region = "US", language = "enUS" },
[154] = { name = "Detheroc", type = "PVP", region = "US", language = "enUS" },
[13] = { name = "Doomhammer", type = "PVE", region = "US", language = "enUS" },
[115] = { name = "Draenor", type = "PVE", region = "US", language = "enUS" },
[114] = { name = "Dragonblight", type = "PVE", region = "US", language = "enUS" },
[84] = { name = "Dragonmaw", type = "PVP", region = "US", language = "enUS" },
[1362] = { name = "Drak'Tharon", type = "PVP", region = "US", language = "enUS" },
[1140] = { name = "Drak'thul", type = "PVE", region = "US", language = "enUS" },
[1139] = { name = "Draka", type = "PVE", region = "US", language = "enUS" },
[1425] = { name = "Drakkari", type = "PVP", region = "US", language = "esMX" },
[1429] = { name = "Dreadmaul", type = "PVP", region = "US", language = "enUS", subregion = "Oceanic" },
[1377] = { name = "Drenden", type = "PVE", region = "US", language = "enUS" },
[111] = { name = "Dunemaul", type = "PVP", region = "US", language = "enUS" },
[63] = { name = "Durotan", type = "PVE", region = "US", language = "enUS" },
[1258] = { name = "Duskwood", type = "PVE", region = "US", language = "enUS" },
[100] = { name = "Earthen Ring", type = "RP", region = "US", language = "enUS" },
[1342] = { name = "Echo Isles", type = "PVE", region = "US", language = "enUS" },
[47] = { name = "Eitrigg", type = "PVE", region = "US", language = "enUS" },
[123] = { name = "Eldre'Thalas", type = "PVE", region = "US", language = "enUS" },
[67] = { name = "Elune", type = "PVE", region = "US", language = "enUS" },
[162] = { name = "Emerald Dream", type = "RPPVP", region = "US", language = "enUS" },
[96] = { name = "Eonar", type = "PVE", region = "US", language = "enUS" },
[93] = { name = "Eredar", type = "PVP", region = "US", language = "enUS" },
[1277] = { name = "Executus", type = "PVP", region = "US", language = "enUS" },
[1565] = { name = "Exodar", type = "PVE", region = "US", language = "enUS" },
[1370] = { name = "Farstriders", type = "RP", region = "US", language = "enUS" },
[118] = { name = "Feathermoon", type = "RP", region = "US", language = "enUS" },
[1345] = { name = "Fenris", type = "PVE", region = "US", language = "enUS" },
[127] = { name = "Firetree", type = "PVP", region = "US", language = "enUS" },
[1576] = { name = "Fizzcrank", type = "PVE", region = "US", language = "enUS" },
[128] = { name = "Frostmane", type = "PVP", region = "US", language = "enUS" },
[1133] = { name = "Frostmourne", type = "PVP", region = "US", language = "enUS", subregion = "Oceanic" },
[7] = { name = "Frostwolf", type = "PVP", region = "US", language = "enUS" },
[1581] = { name = "Galakrond", type = "PVE", region = "US", language = "enUS" },
[3234] = { name = "Gallywix", type = "PVE", region = "US", language = "ptBR" },
[1141] = { name = "Garithos", type = "PVP", region = "US", language = "enUS" },
[51] = { name = "Garona", type = "PVE", region = "US", language = "enUS" },
[1373] = { name = "Garrosh", type = "PVE", region = "US", language = "enUS" },
[1578] = { name = "Ghostlands", type = "PVE", region = "US", language = "enUS" },
[97] = { name = "Gilneas", type = "PVE", region = "US", language = "enUS" },
[1287] = { name = "Gnomeregan", type = "PVE", region = "US", language = "enUS" },
[3207] = { name = "Goldrinn", type = "PVE", region = "US", language = "ptBR" },
[92] = { name = "Gorefiend", type = "PVP", region = "US", language = "enUS" },
[80] = { name = "Gorgonnash", type = "PVP", region = "US", language = "enUS" },
[158] = { name = "Greymane", type = "PVE", region = "US", language = "enUS" },
[1579] = { name = "Grizzly Hills", type = "PVE", region = "US", language = "enUS" },
[1068] = { name = "Gul'dan", type = "PVP", region = "US", language = "enUS" },
[1149] = { name = "Gundrak", type = "PVP", region = "US", language = "enUS", subregion = "Oceanic" },
[129] = { name = "Gurubashi", type = "PVP", region = "US", language = "enUS" },
[1142] = { name = "Hakkar", type = "PVP", region = "US", language = "enUS" },
[1266] = { name = "Haomarush", type = "PVP", region = "US", language = "enUS" },
[53] = { name = "Hellscream", type = "PVE", region = "US", language = "enUS" },
[1368] = { name = "Hydraxis", type = "PVE", region = "US", language = "enUS" },
[6] = { name = "Hyjal", type = "PVE", region = "US", language = "enUS" },
[14] = { name = "Icecrown", type = "PVE", region = "US", language = "enUS" },
[57] = { name = "Illidan", type = "PVP", region = "US", language = "enUS" },
[3661] = { name = "Internal Record 3661", type = "PVE", region = "US", language = "enUS" },
[3675] = { name = "Internal Record 3675", type = "RP", region = "US", language = "enUS" },
[3676] = { name = "Internal Record 3676", type = "PVE", region = "US", language = "enUS" },
[3677] = { name = "Internal Record 3677", type = "PVE", region = "US", language = "enUS" },
[3678] = { name = "Internal Record 3678", type = "PVE", region = "US", language = "enUS" },
[1291] = { name = "Jaedenar", type = "PVP", region = "US", language = "enUS" },
[1144] = { name = "Jubei'Thos", type = "PVP", region = "US", language = "enUS", subregion = "Oceanic" },
[1069] = { name = "Kael'thas", type = "PVE", region = "US", language = "enUS" },
[155] = { name = "Kalecgos", type = "PVP", region = "US", language = "enUS" },
[98] = { name = "Kargath", type = "PVE", region = "US", language = "enUS" },
[16] = { name = "Kel'Thuzad", type = "PVP", region = "US", language = "enUS" },
[65] = { name = "Khadgar", type = "PVE", region = "US", language = "enUS" },
[1143] = { name = "Khaz Modan", type = "PVE", region = "US", language = "enUS" },
[1134] = { name = "Khaz'goroth", type = "PVE", region = "US", language = "enUS", subregion = "Oceanic" },
[9] = { name = "Kil'jaeden", type = "PVP", region = "US", language = "enUS" },
[4] = { name = "Kilrogg", type = "PVE", region = "US", language = "enUS" },
[1071] = { name = "Kirin Tor", type = "RP", region = "US", language = "enUS" },
[1146] = { name = "Korgath", type = "PVP", region = "US", language = "enUS" },
[1349] = { name = "Korialstrasz", type = "PVE", region = "US", language = "enUS" },
[1147] = { name = "Kul Tiras", type = "PVE", region = "US", language = "enUS" },
[101] = { name = "Laughing Skull", type = "PVP", region = "US", language = "enUS" },
[1295] = { name = "Lethon", type = "PVP", region = "US", language = "enUS" },
[1] = { name = "Lightbringer", type = "PVE", region = "US", language = "enUS" },
[95] = { name = "Lightning's Blade", type = "PVP", region = "US", language = "enUS" },
[1130] = { name = "Lightninghoof", type = "RPPVP", region = "US", language = "enUS" },
[99] = { name = "Llane", type = "PVE", region = "US", language = "enUS" },
[68] = { name = "Lothar", type = "PVE", region = "US", language = "enUS" },
[1173] = { name = "Madoran", type = "PVE", region = "US", language = "enUS" },
[163] = { name = "Maelstrom", type = "RPPVP", region = "US", language = "enUS" },
[78] = { name = "Magtheridon", type = "PVP", region = "US", language = "enUS" },
[1357] = { name = "Maiev", type = "PVP", region = "US", language = "enUS" },
[59] = { name = "Mal'Ganis", type = "PVP", region = "US", language = "enUS" },
[1132] = { name = "Malfurion", type = "PVE", region = "US", language = "enUS" },
[1148] = { name = "Malorne", type = "PVP", region = "US", language = "enUS" },
[104] = { name = "Malygos", type = "PVE", region = "US", language = "enUS" },
[70] = { name = "Mannoroth", type = "PVP", region = "US", language = "enUS" },
[62] = { name = "Medivh", type = "PVE", region = "US", language = "enUS" },
[1350] = { name = "Misha", type = "PVE", region = "US", language = "enUS" },
[1374] = { name = "Mok'Nathal", type = "PVE", region = "US", language = "enUS" },
[1365] = { name = "Moon Guard", type = "RP", region = "US", language = "enUS" },
[153] = { name = "Moonrunner", type = "PVE", region = "US", language = "enUS" },
[1145] = { name = "Mug'thol", type = "PVP", region = "US", language = "enUS" },
[1182] = { name = "Muradin", type = "PVE", region = "US", language = "enUS" },
[1432] = { name = "Nagrand", type = "PVE", region = "US", language = "enUS", subregion = "Oceanic" },
[89] = { name = "Nathrezim", type = "PVP", region = "US", language = "enUS" },
[1169] = { name = "Naxxramas", type = "RP", region = "US", language = "enUS" },
[1367] = { name = "Nazgrel", type = "PVE", region = "US", language = "enUS" },
[1131] = { name = "Nazjatar", type = "PVP", region = "US", language = "enUS" },
[3208] = { name = "Nemesis", type = "PVP", region = "US", language = "ptBR" },
[8] = { name = "Ner'zhul", type = "PVP", region = "US", language = "enUS" },
[1375] = { name = "Nesingwary", type = "PVE", region = "US", language = "enUS" },
[1359] = { name = "Nordrassil", type = "PVE", region = "US", language = "enUS" },
[1262] = { name = "Norgannon", type = "PVE", region = "US", language = "enUS" },
[1285] = { name = "Onyxia", type = "PVP", region = "US", language = "enUS" },
[122] = { name = "Perenolde", type = "PVE", region = "US", language = "enUS" },
[5] = { name = "Proudmoore", type = "PVE", region = "US", language = "enUS" },
[1428] = { name = "Quel'Thalas", type = "PVE", region = "US", language = "esMX" },
[1372] = { name = "Quel'dorei", type = "PVE", region = "US", language = "enUS" },
[1427] = { name = "Ragnaros", type = "PVP", region = "US", language = "esMX" },
[1072] = { name = "Ravencrest", type = "PVE", region = "US", language = "enUS" },
[1352] = { name = "Ravenholdt", type = "RPPVP", region = "US", language = "enUS" },
[1151] = { name = "Rexxar", type = "PVE", region = "US", language = "enUS" },
[1358] = { name = "Rivendare", type = "PVP", region = "US", language = "enUS" },
[151] = { name = "Runetotem", type = "PVE", region = "US", language = "enUS" },
[76] = { name = "Sargeras", type = "PVP", region = "US", language = "enUS" },
[1153] = { name = "Saurfang", type = "PVE", region = "US", language = "enUS", subregion = "Oceanic" },
[126] = { name = "Scarlet Crusade", type = "RP", region = "US", language = "enUS" },
[1267] = { name = "Scilla", type = "PVP", region = "US", language = "enUS" },
[1185] = { name = "Sen'jin", type = "PVE", region = "US", language = "enUS" },
[1290] = { name = "Sentinels", type = "RP", region = "US", language = "enUS" },
[125] = { name = "Shadow Council", type = "RP", region = "US", language = "enUS" },
[94] = { name = "Shadowmoon", type = "PVP", region = "US", language = "enUS" },
[85] = { name = "Shadowsong", type = "PVE", region = "US", language = "enUS" },
[1364] = { name = "Shandris", type = "PVE", region = "US", language = "enUS" },
[1557] = { name = "Shattered Halls", type = "PVP", region = "US", language = "enUS" },
[72] = { name = "Shattered Hand", type = "PVP", region = "US", language = "enUS" },
[1354] = { name = "Shu'halo", type = "PVE", region = "US", language = "enUS" },
[12] = { name = "Silver Hand", type = "RP", region = "US", language = "enUS" },
[86] = { name = "Silvermoon", type = "PVE", region = "US", language = "enUS" },
[1356] = { name = "Sisters of Elune", type = "RP", region = "US", language = "enUS" },
[74] = { name = "Skullcrusher", type = "PVP", region = "US", language = "enUS" },
[131] = { name = "Skywall", type = "PVE", region = "US", language = "enUS" },
[130] = { name = "Smolderthorn", type = "PVP", region = "US", language = "enUS" },
[82] = { name = "Spinebreaker", type = "PVP", region = "US", language = "enUS" },
[124] = { name = "Spirestone", type = "PVP", region = "US", language = "enUS" },
[160] = { name = "Staghelm", type = "PVE", region = "US", language = "enUS" },
[1260] = { name = "Steamwheedle Cartel", type = "RP", region = "US", language = "enUS" },
[108] = { name = "Stonemaul", type = "PVP", region = "US", language = "enUS" },
[60] = { name = "Stormrage", type = "PVE", region = "US", language = "enUS" },
[58] = { name = "Stormreaver", type = "PVP", region = "US", language = "enUS" },
[110] = { name = "Stormscale", type = "PVP", region = "US", language = "enUS" },
[113] = { name = "Suramar", type = "PVE", region = "US", language = "enUS" },
[1292] = { name = "Tanaris", type = "PVE", region = "US", language = "enUS" },
[90] = { name = "Terenas", type = "PVE", region = "US", language = "enUS" },
[1563] = { name = "Terokkar", type = "PVE", region = "US", language = "enUS" },
[1433] = { name = "Thaurissan", type = "PVP", region = "US", language = "enUS", subregion = "Oceanic" },
[1344] = { name = "The Forgotten Coast", type = "PVP", region = "US", language = "enUS" },
[1570] = { name = "The Scryers", type = "RP", region = "US", language = "enUS" },
[1559] = { name = "The Underbog", type = "PVP", region = "US", language = "enUS" },
[1289] = { name = "The Venture Co", type = "RPPVP", region = "US", language = "enUS" },
[1154] = { name = "Thorium Brotherhood", type = "RP", region = "US", language = "enUS" },
[1263] = { name = "Thrall", type = "PVE", region = "US", language = "enUS" },
[105] = { name = "Thunderhorn", type = "PVE", region = "US", language = "enUS" },
[103] = { name = "Thunderlord", type = "PVP", region = "US", language = "enUS" },
[11] = { name = "Tichondrius", type = "PVP", region = "US", language = "enUS" },
[3210] = { name = "Tol Barad", type = "PVP", region = "US", language = "ptBR" },
[1360] = { name = "Tortheldrin", type = "PVP", region = "US", language = "enUS" },
[1175] = { name = "Trollbane", type = "PVE", region = "US", language = "enUS" },
[1265] = { name = "Turalyon", type = "PVE", region = "US", language = "enUS" },
[164] = { name = "Twisting Nether", type = "RPPVP", region = "US", language = "enUS" },
[1283] = { name = "Uldaman", type = "PVE", region = "US", language = "enUS" },
[116] = { name = "Uldum", type = "PVE", region = "US", language = "enUS" },
[1294] = { name = "Undermine", type = "PVE", region = "US", language = "enUS" },
[156] = { name = "Ursin", type = "PVP", region = "US", language = "enUS" },
[3] = { name = "Uther", type = "PVE", region = "US", language = "enUS" },
[1348] = { name = "Vashj", type = "PVP", region = "US", language = "enUS" },
[1184] = { name = "Vek'nilash", type = "PVE", region = "US", language = "enUS" },
[1567] = { name = "Velen", type = "PVE", region = "US", language = "enUS" },
[71] = { name = "Warsong", type = "PVP", region = "US", language = "enUS" },
[55] = { name = "Whisperwind", type = "PVE", region = "US", language = "enUS" },
[159] = { name = "Wildhammer", type = "PVP", region = "US", language = "enUS" },
[87] = { name = "Windrunner", type = "PVE", region = "US", language = "enUS" },
[1355] = { name = "Winterhoof", type = "PVE", region = "US", language = "enUS" },
[1369] = { name = "Wyrmrest Accord", type = "RP", region = "US", language = "enUS" },
[1174] = { name = "Xavius", type = "PVE", region = "US", language = "enUS" },
[1270] = { name = "Ysera", type = "PVE", region = "US", language = "enUS" },
[1268] = { name = "Ysondre", type = "PVP", region = "US", language = "enUS" },
[1572] = { name = "Zangarmarsh", type = "PVE", region = "US", language = "enUS" },
[61] = { name = "Zul'jin", type = "PVE", region = "US", language = "enUS" },
[1259] = { name = "Zuluhed", type = "PVP", region = "US", language = "enUS" },
--}}

--{{ EUROPE ------------------------------------------------------------
[577] = { name = "Aegwynn", type = "PVP", region = "EU", language = "deDE" },
[1312] = { name = "Aerie Peak", type = "PVE", region = "EU", language = "enGB" },
[518] = { name = "Agamaggan", type = "PVP", region = "EU", language = "enGB" },
[1413] = { name = "Aggra (Português)", type = "PVP", region = "EU", language = "ptPT" },
[500] = { name = "Aggramar", type = "PVE", region = "EU", language = "enGB" },
[1093] = { name = "Ahn'Qiraj", type = "PVP", region = "EU", language = "enGB" },
[519] = { name = "Al'Akir", type = "PVP", region = "EU", language = "enGB" },
[562] = { name = "Alexstrasza", type = "PVE", region = "EU", language = "deDE" },
[563] = { name = "Alleria", type = "PVE", region = "EU", language = "deDE" },
[1391] = { name = "Alonsus", type = "PVE", region = "EU", language = "enGB" },
[601] = { name = "Aman'Thul", type = "PVE", region = "EU", language = "deDE" },
[1330] = { name = "Ambossar", type = "PVE", region = "EU", language = "deDE" },
[1394] = { name = "Anachronos", type = "PVE", region = "EU", language = "enGB" },
[1104] = { name = "Anetheron", type = "PVP", region = "EU", language = "deDE" },
[564] = { name = "Antonidas", type = "PVE", region = "EU", language = "deDE" },
[608] = { name = "Anub'arak", type = "PVP", region = "EU", language = "deDE" },
[512] = { name = "Arak-arahm", type = "PVP", region = "EU", language = "frFR" },
[1334] = { name = "Arathi", type = "PVP", region = "EU", language = "frFR" },
[501] = { name = "Arathor", type = "PVE", region = "EU", language = "enGB" },
[539] = { name = "Archimonde", type = "PVP", region = "EU", language = "frFR" },
[1404] = { name = "Area 52", type = "PVE", region = "EU", language = "deDE" },
[536] = { name = "Argent Dawn", type = "RP", region = "EU", language = "enGB" },
[578] = { name = "Arthas", type = "PVP", region = "EU", language = "deDE" },
[1406] = { name = "Arygos", type = "PVE", region = "EU", language = "deDE" },
[1923] = { name = "Ashenvale", type = "PVP", region = "EU", language = "ruRU" },
[502] = { name = "Aszune", type = "PVE", region = "EU", language = "enGB" },
[1597] = { name = "Auchindoun", type = "PVP", region = "EU", language = "enGB" },
[503] = { name = "Azjol-Nerub", type = "PVE", region = "EU", language = "enGB" },
[579] = { name = "Azshara", type = "PVP", region = "EU", language = "deDE" },
[1922] = { name = "Azuregos", type = "PVE", region = "EU", language = "ruRU" },
[1417] = { name = "Azuremyst", type = "PVE", region = "EU", language = "enGB" },
[565] = { name = "Baelgun", type = "PVE", region = "EU", language = "deDE" },
[607] = { name = "Balnazzar", type = "PVP", region = "EU", language = "enGB" },
[566] = { name = "Blackhand", type = "PVE", region = "EU", language = "deDE" },
[580] = { name = "Blackmoore", type = "PVP", region = "EU", language = "deDE" },
[581] = { name = "Blackrock", type = "PVP", region = "EU", language = "deDE" },
[1929] = { name = "Blackscar", type = "PVP", region = "EU", language = "ruRU" },
[1416] = { name = "Blade's Edge", type = "PVE", region = "EU", language = "enGB" },
[521] = { name = "Bladefist", type = "PVP", region = "EU", language = "enGB" },
[630] = { name = "Bloodfeather", type = "PVP", region = "EU", language = "enGB" },
[504] = { name = "Bloodhoof", type = "PVE", region = "EU", language = "enGB" },
[522] = { name = "Bloodscalp", type = "PVP", region = "EU", language = "enGB" },
[1613] = { name = "Blutkessel", type = "PVP", region = "EU", language = "deDE" },
[1924] = { name = "Booty Bay", type = "PVP", region = "EU", language = "ruRU" },
[1625] = { name = "Borean Tundra", type = "PVE", region = "EU", language = "ruRU" },
[1299] = { name = "Boulderfist", type = "PVP", region = "EU", language = "enGB" },
[1393] = { name = "Bronze Dragonflight", type = "PVE", region = "EU", language = "enGB" },
[1081] = { name = "Bronzebeard", type = "PVE", region = "EU", language = "enGB" },
[523] = { name = "Burning Blade", type = "PVP", region = "EU", language = "enGB" },
[524] = { name = "Burning Legion", type = "PVP", region = "EU", language = "enGB" },
[1392] = { name = "Burning Steppes", type = "PVP", region = "EU", language = "enGB" },
[1381] = { name = "C'Thun", type = "PVP", region = "EU", language = "esES" },
[1315] = { name = "Caduta dei Draghi", type = "PVE", region = "EU", language = "frFR" },
[1307] = { name = "Chamber of Aspects", type = "PVE", region = "EU", language = "enGB" },
[1620] = { name = "Chants éternels", type = "PVE", region = "EU", language = "frFR" },
[545] = { name = "Cho'gall", type = "PVP", region = "EU", language = "frFR" },
[1083] = { name = "Chromaggus", type = "PVP", region = "EU", language = "enGB" },
[1395] = { name = "Colinas Pardas", type = "PVE", region = "EU", language = "esES" },
[1127] = { name = "Confrérie du Thorium", type = "RP", region = "EU", language = "frFR" },
[644] = { name = "Conseil des Ombres", type = "RPPVP", region = "EU", language = "frFR" },
[525] = { name = "Crushridge", type = "PVP", region = "EU", language = "enGB" },
[1337] = { name = "Culte de la Rive noire", type = "RPPVP", region = "EU", language = "frFR" },
[526] = { name = "Daggerspine", type = "PVP", region = "EU", language = "enGB" },
[538] = { name = "Dalaran", type = "PVE", region = "EU", language = "frFR" },
[1321] = { name = "Dalvengyr", type = "PVP", region = "EU", language = "deDE" },
[1317] = { name = "Darkmoon Faire", type = "RP", region = "EU", language = "enGB" },
[631] = { name = "Darksorrow", type = "PVP", region = "EU", language = "enGB" },
[1389] = { name = "Darkspear", type = "PVE", region = "EU", language = "enGB" },
[1619] = { name = "Das Konsortium", type = "RPPVP", region = "EU", language = "deDE" },
[614] = { name = "Das Syndikat", type = "RPPVP", region = "EU", language = "deDE" },
[1605] = { name = "Deathguard", type = "PVP", region = "EU", language = "ruRU" },
[1617] = { name = "Deathweaver", type = "PVP", region = "EU", language = "ruRU" },
[527] = { name = "Deathwing", type = "PVP", region = "EU", language = "enGB" },
[1609] = { name = "Deepholm", type = "PVP", region = "EU", language = "ruRU" },
[635] = { name = "Defias Brotherhood", type = "RPPVP", region = "EU", language = "enGB" },
[1084] = { name = "Dentarg", type = "PVP", region = "EU", language = "enGB" },
[1327] = { name = "Der Mithrilorden", type = "RP", region = "EU", language = "deDE" },
[617] = { name = "Der Rat von Dalaran", type = "RP", region = "EU", language = "deDE" },
[1326] = { name = "Der abyssische Rat", type = "RPPVP", region = "EU", language = "deDE" },
[582] = { name = "Destromath", type = "PVP", region = "EU", language = "deDE" },
[531] = { name = "Dethecus", type = "PVP", region = "EU", language = "deDE" },
[1618] = { name = "Die Aldor", type = "RP", region = "EU", language = "deDE" },
[1121] = { name = "Die Arguswacht", type = "RPPVP", region = "EU", language = "deDE" },
[1333] = { name = "Die Nachtwache", type = "RP", region = "EU", language = "deDE" },
[576] = { name = "Die Silberne Hand", type = "RP", region = "EU", language = "deDE" },
[1119] = { name = "Die Todeskrallen", type = "RPPVP", region = "EU", language = "deDE" },
[1118] = { name = "Die ewige Wacht", type = "RP", region = "EU", language = "deDE" },
[505] = { name = "Doomhammer", type = "PVE", region = "EU", language = "enGB" },
[506] = { name = "Draenor", type = "PVE", region = "EU", language = "enGB" },
[507] = { name = "Dragonblight", type = "PVE", region = "EU", language = "enGB" },
[528] = { name = "Dragonmaw", type = "PVP", region = "EU", language = "enGB" },
[1092] = { name = "Drak'thul", type = "PVP", region = "EU", language = "enGB" },
[641] = { name = "Drek'Thar", type = "PVE", region = "EU", language = "frFR" },
[1378] = { name = "Dun Modr", type = "PVP", region = "EU", language = "esES" },
[600] = { name = "Dun Morogh", type = "PVE", region = "EU", language = "deDE" },
[529] = { name = "Dunemaul", type = "PVP", region = "EU", language = "enGB" },
[535] = { name = "Durotan", type = "PVE", region = "EU", language = "deDE" },
[561] = { name = "Earthen Ring", type = "RP", region = "EU", language = "enGB" },
[1612] = { name = "Echsenkessel", type = "PVP", region = "EU", language = "deDE" },
[1123] = { name = "Eitrigg", type = "PVE", region = "EU", language = "frFR" },
[1336] = { name = "Eldre'Thalas", type = "PVP", region = "EU", language = "frFR" },
[540] = { name = "Elune", type = "PVE", region = "EU", language = "frFR" },
[508] = { name = "Emerald Dream", type = "PVE", region = "EU", language = "enGB" },
[1091] = { name = "Emeriss", type = "PVP", region = "EU", language = "enGB" },
[1310] = { name = "Eonar", type = "PVE", region = "EU", language = "enGB" },
[583] = { name = "Eredar", type = "PVP", region = "EU", language = "deDE" },
[1654] = { name = "Euskal Encounter", type = "PVE", region = "EU", language = "esES" },
[1925] = { name = "Eversong", type = "PVE", region = "EU", language = "ruRU" },
[1087] = { name = "Executus", type = "PVP", region = "EU", language = "enGB" },
[1385] = { name = "Exodar", type = "PVE", region = "EU", language = "esES" },
[1611] = { name = "Festung der Stürme", type = "PVP", region = "EU", language = "deDE" },
[1623] = { name = "Fordragon", type = "PVE", region = "EU", language = "ruRU" },
[516] = { name = "Forscherliga", type = "RP", region = "EU", language = "deDE" },
[1300] = { name = "Frostmane", type = "PVP", region = "EU", language = "enGB" },
[584] = { name = "Frostmourne", type = "PVP", region = "EU", language = "deDE" },
[632] = { name = "Frostwhisper", type = "PVP", region = "EU", language = "enGB" },
[585] = { name = "Frostwolf", type = "PVP", region = "EU", language = "deDE" },
[1614] = { name = "Galakrond", type = "PVE", region = "EU", language = "ruRU" },
[509] = { name = "Garona", type = "PVP", region = "EU", language = "frFR" },
[1401] = { name = "Garrosh", type = "PVE", region = "EU", language = "deDE" },
[606] = { name = "Genjuros", type = "PVP", region = "EU", language = "enGB" },
[1588] = { name = "Ghostlands", type = "PVE", region = "EU", language = "enGB" },
[567] = { name = "Gilneas", type = "PVE", region = "EU", language = "deDE" },
[1928] = { name = "Goldrinn", type = "PVE", region = "EU", language = "ruRU" },
[1602] = { name = "Gordunni", type = "PVP", region = "EU", language = "ruRU" },
[586] = { name = "Gorgonnash", type = "PVP", region = "EU", language = "deDE" },
[1610] = { name = "Greymane", type = "PVP", region = "EU", language = "ruRU" },
[1303] = { name = "Grim Batol", type = "PVP", region = "EU", language = "enGB" },
[1325] = { name = "Grizzlyhügel", type = "PVE", region = "EU", language = "enGB" },
[1927] = { name = "Grom", type = "PVP", region = "EU", language = "ruRU" },
[587] = { name = "Gul'dan", type = "PVP", region = "EU", language = "deDE" },
[646] = { name = "Hakkar", type = "PVP", region = "EU", language = "enGB" },
[638] = { name = "Haomarush", type = "PVP", region = "EU", language = "enGB" },
[1587] = { name = "Hellfire", type = "PVE", region = "EU", language = "enGB" },
[619] = { name = "Hellscream", type = "PVE", region = "EU", language = "enGB" },
[1615] = { name = "Howling Fjord", type = "PVP", region = "EU", language = "ruRU" },
[542] = { name = "Hyjal", type = "PVE", region = "EU", language = "frFR" },
[541] = { name = "Illidan", type = "PVP", region = "EU", language = "frFR" },
[3656] = { name = "Internal Record 3656", type = "PVP", region = "EU", language = "enGB" },
[3657] = { name = "Internal Record 3657", type = "PVP", region = "EU", language = "enGB" },
[3660] = { name = "Internal Record 3660", type = "PVP", region = "EU", language = "enGB" },
[3666] = { name = "Internal Record 3666", type = "PVE", region = "EU", language = "enGB" },
[3674] = { name = "Internal Record 3674", type = "PVP", region = "EU", language = "enGB" },
[1304] = { name = "Jaedenar", type = "PVP", region = "EU", language = "enGB" },
[543] = { name = "Kael'thas", type = "PVP", region = "EU", language = "frFR" },
[1596] = { name = "Karazhan", type = "PVP", region = "EU", language = "enGB" },
[568] = { name = "Kargath", type = "PVE", region = "EU", language = "deDE" },
[1305] = { name = "Kazzak", type = "PVP", region = "EU", language = "enGB" },
[588] = { name = "Kel'Thuzad", type = "PVP", region = "EU", language = "deDE" },
[1080] = { name = "Khadgar", type = "PVE", region = "EU", language = "enGB" },
[640] = { name = "Khaz Modan", type = "PVE", region = "EU", language = "frFR" },
[569] = { name = "Khaz'goroth", type = "PVE", region = "EU", language = "deDE" },
[589] = { name = "Kil'jaeden", type = "PVP", region = "EU", language = "deDE" },
[1311] = { name = "Kilrogg", type = "PVE", region = "EU", language = "enGB" },
[537] = { name = "Kirin Tor", type = "RP", region = "EU", language = "frFR" },
[633] = { name = "Kor'gall", type = "PVP", region = "EU", language = "enGB" },
[616] = { name = "Krag'jin", type = "PVP", region = "EU", language = "deDE" },
[1332] = { name = "Krasus", type = "PVE", region = "EU", language = "frFR" },
[1082] = { name = "Kul Tiras", type = "PVE", region = "EU", language = "enGB" },
[613] = { name = "Kult der Verdammten", type = "RPPVP", region = "EU", language = "deDE" },
[1086] = { name = "La Croisade écarlate", type = "RPPVP", region = "EU", language = "frFR" },
[621] = { name = "Laughing Skull", type = "PVP", region = "EU", language = "enGB" },
[1626] = { name = "Les Clairvoyants", type = "RP", region = "EU", language = "frFR" },
[647] = { name = "Les Sentinelles", type = "RP", region = "EU", language = "frFR" },
[1603] = { name = "Lich King", type = "PVP", region = "EU", language = "ruRU" },
[1388] = { name = "Lightbringer", type = "PVE", region = "EU", language = "enGB" },
[637] = { name = "Lightning's Blade", type = "PVP", region = "EU", language = "enGB" },
[1409] = { name = "Lordaeron", type = "PVE", region = "EU", language = "deDE" },
[1387] = { name = "Los Errantes", type = "PVE", region = "EU", language = "esES" },
[570] = { name = "Lothar", type = "PVE", region = "EU", language = "deDE" },
[571] = { name = "Madmortem", type = "PVE", region = "EU", language = "deDE" },
[622] = { name = "Magtheridon", type = "PVE", region = "EU", language = "enGB" },
[590] = { name = "Mal'Ganis", type = "PVP", region = "EU", language = "deDE" },
[572] = { name = "Malfurion", type = "PVE", region = "EU", language = "deDE" },
[1324] = { name = "Malorne", type = "PVE", region = "EU", language = "deDE" },
[1098] = { name = "Malygos", type = "PVE", region = "EU", language = "deDE" },
[591] = { name = "Mannoroth", type = "PVP", region = "EU", language = "deDE" },
[1621] = { name = "Marécage de Zangar", type = "PVE", region = "EU", language = "frFR" },
[1089] = { name = "Mazrigos", type = "PVE", region = "EU", language = "enGB" },
[517] = { name = "Medivh", type = "PVE", region = "EU", language = "frFR" },
[1386] = { name = "Minahonda", type = "PVE", region = "EU", language = "esES" },
[1396] = { name = "Molten Core", type = "PVE", region = "EU", language = "enGB" },
[1085] = { name = "Moonglade", type = "RP", region = "EU", language = "enGB" },
[1319] = { name = "Mug'thol", type = "PVP", region = "EU", language = "deDE" },
[1329] = { name = "Muradin", type = "PVP", region = "EU", language = "enGB" },
[1589] = { name = "Nagrand", type = "PVE", region = "EU", language = "enGB" },
[594] = { name = "Nathrezim", type = "PVP", region = "EU", language = "deDE" },
[1624] = { name = "Naxxramas", type = "PVP", region = "EU", language = "frFR" },
[1105] = { name = "Nazjatar", type = "PVP", region = "EU", language = "deDE" },
[612] = { name = "Nefarian", type = "PVP", region = "EU", language = "deDE" },
[1316] = { name = "Nemesis", type = "PVP", region = "EU", language = "itIT" },
[624] = { name = "Neptulon", type = "PVP", region = "EU", language = "enGB" },
[544] = { name = "Ner'zhul", type = "PVP", region = "EU", language = "frFR" },
[611] = { name = "Nera'thor", type = "PVP", region = "EU", language = "deDE" },
[1607] = { name = "Nethersturm", type = "PVE", region = "EU", language = "deDE" },
[618] = { name = "Nordrassil", type = "PVE", region = "EU", language = "enGB" },
[1408] = { name = "Norgannon", type = "PVE", region = "EU", language = "deDE" },
[574] = { name = "Nozdormu", type = "PVE", region = "EU", language = "deDE" },
[610] = { name = "Onyxia", type = "PVP", region = "EU", language = "deDE" },
[1301] = { name = "Outland", type = "PVP", region = "EU", language = "enGB" },
[575] = { name = "Perenolde", type = "PVE", region = "EU", language = "deDE" },
[1309] = { name = "Pozzo dell'Eternità", type = "PVE", region = "EU", language = "itIT" },
[593] = { name = "Proudmoore", type = "PVE", region = "EU", language = "deDE" },
[623] = { name = "Quel'Thalas", type = "PVE", region = "EU", language = "enGB" },
[626] = { name = "Ragnaros", type = "PVP", region = "EU", language = "enGB" },
[1322] = { name = "Rajaxx", type = "PVP", region = "EU", language = "deDE" },
[642] = { name = "Rashgarroth", type = "PVP", region = "EU", language = "frFR" },
[554] = { name = "Ravencrest", type = "PVP", region = "EU", language = "enGB" },
[1308] = { name = "Ravenholdt", type = "RPPVP", region = "EU", language = "enGB" },
[1616] = { name = "Razuvious", type = "PVP", region = "EU", language = "ruRU" },
[1099] = { name = "Rexxar", type = "PVE", region = "EU", language = "deDE" },
[547] = { name = "Runetotem", type = "PVE", region = "EU", language = "enGB" },
[1382] = { name = "Sanguino", type = "PVP", region = "EU", language = "esES" },
[546] = { name = "Sargeras", type = "PVP", region = "EU", language = "frFR" },
[1314] = { name = "Saurfang", type = "PVE", region = "EU", language = "enGB" },
[1096] = { name = "Scarshield Legion", type = "RPPVP", region = "EU", language = "enGB" },
[602] = { name = "Sen'jin", type = "PVE", region = "EU", language = "deDE" },
[555] = { name = "Shadowmoon", type = "PVP", region = "EU", language = "enGB" },
[548] = { name = "Shadowsong", type = "PVE", region = "EU", language = "enGB" },
[1598] = { name = "Shattered Halls", type = "PVP", region = "EU", language = "enGB" },
[556] = { name = "Shattered Hand", type = "PVP", region = "EU", language = "enGB" },
[1608] = { name = "Shattrath", type = "PVE", region = "EU", language = "deDE" },
[1383] = { name = "Shen'dralar", type = "PVP", region = "EU", language = "esES" },
[549] = { name = "Silvermoon", type = "PVE", region = "EU", language = "enGB" },
[533] = { name = "Sinstralis", type = "PVP", region = "EU", language = "frFR" },
[557] = { name = "Skullcrusher", type = "PVP", region = "EU", language = "enGB" },
[1604] = { name = "Soulflayer", type = "PVP", region = "EU", language = "ruRU" },
[558] = { name = "Spinebreaker", type = "PVP", region = "EU", language = "enGB" },
[1606] = { name = "Sporeggar", type = "RPPVP", region = "EU", language = "enGB" },
[1117] = { name = "Steamwheedle Cartel", type = "RP", region = "EU", language = "enGB" },
[1302] = { name = "Stonemaul", type = "PVP", region = "EU", language = "frFR" },
[550] = { name = "Stormrage", type = "PVE", region = "EU", language = "enGB" },
[559] = { name = "Stormreaver", type = "PVP", region = "EU", language = "enGB" },
[560] = { name = "Stormscale", type = "PVP", region = "EU", language = "enGB" },
[511] = { name = "Sunstrider", type = "PVP", region = "EU", language = "enGB" },
[1331] = { name = "Suramar", type = "PVE", region = "EU", language = "frFR" },
[628] = { name = "Sylvanas", type = "PVP", region = "EU", language = "enGB" },
[1320] = { name = "Taerar", type = "PVP", region = "EU", language = "deDE" },
[1090] = { name = "Talnivarr", type = "PVP", region = "EU", language = "enGB" },
[1306] = { name = "Tarren Mill", type = "PVP", region = "EU", language = "enGB" },
[1407] = { name = "Teldrassil", type = "PVE", region = "EU", language = "deDE" },
[1622] = { name = "Temple noir", type = "PVP", region = "EU", language = "frFR" },
[551] = { name = "Terenas", type = "PVE", region = "EU", language = "enGB" },
[1415] = { name = "Terokkar", type = "PVE", region = "EU", language = "enGB" },
[615] = { name = "Terrordar", type = "PVP", region = "EU", language = "deDE" },
[627] = { name = "The Maelstrom", type = "PVP", region = "EU", language = "enGB" },
[1595] = { name = "The Sha'tar", type = "RP", region = "EU", language = "enGB" },
[636] = { name = "The Venture Co", type = "RPPVP", region = "EU", language = "enGB" },
[605] = { name = "Theradras", type = "PVP", region = "EU", language = "deDE" },
[1926] = { name = "Thermaplugg", type = "PVP", region = "EU", language = "ruRU" },
[604] = { name = "Thrall", type = "PVE", region = "EU", language = "deDE" },
[643] = { name = "Throk'Feroth", type = "PVP", region = "EU", language = "frFR" },
[552] = { name = "Thunderhorn", type = "PVE", region = "EU", language = "enGB" },
[1106] = { name = "Tichondrius", type = "PVE", region = "EU", language = "deDE" },
[1328] = { name = "Tirion", type = "PVE", region = "EU", language = "deDE" },
[1405] = { name = "Todeswache", type = "RP", region = "EU", language = "deDE" },
[1088] = { name = "Trollbane", type = "PVP", region = "EU", language = "enGB" },
[553] = { name = "Turalyon", type = "PVE", region = "EU", language = "enGB" },
[513] = { name = "Twilight's Hammer", type = "PVP", region = "EU", language = "enGB" },
[625] = { name = "Twisting Nether", type = "PVP", region = "EU", language = "enGB" },
[1384] = { name = "Tyrande", type = "PVE", region = "EU", language = "esES" },
[1122] = { name = "Uldaman", type = "PVE", region = "EU", language = "frFR" },
[1323] = { name = "Ulduar", type = "PVE", region = "EU", language = "deDE" },
[1380] = { name = "Uldum", type = "PVP", region = "EU", language = "esES" },
[1400] = { name = "Un'Goro", type = "PVE", region = "EU", language = "deDE" },
[645] = { name = "Varimathras", type = "PVE", region = "EU", language = "frFR" },
[629] = { name = "Vashj", type = "PVP", region = "EU", language = "enGB" },
[1318] = { name = "Vek'lor", type = "PVP", region = "EU", language = "deDE" },
[1298] = { name = "Vek'nilash", type = "PVE", region = "EU", language = "enGB" },
[510] = { name = "Vol'jin", type = "PVE", region = "EU", language = "frFR" },
[1313] = { name = "Wildhammer", type = "PVE", region = "EU", language = "enGB" },
[609] = { name = "Wrathbringer", type = "PVP", region = "EU", language = "deDE" },
[639] = { name = "Xavius", type = "PVP", region = "EU", language = "enGB" },
[1097] = { name = "Ysera", type = "PVE", region = "EU", language = "deDE" },
[1335] = { name = "Ysondre", type = "PVP", region = "EU", language = "frFR" },
[515] = { name = "Zenedar", type = "PVP", region = "EU", language = "enGB" },
[592] = { name = "Zirkel des Cenarius", type = "RP", region = "EU", language = "deDE" },
[1379] = { name = "Zul'jin", type = "PVP", region = "EU", language = "esES" },
[573] = { name = "Zuluhed", type = "PVP", region = "EU", language = "deDE" },
--}}
}